"""The five-verb Deletion Participant Contract (ARCHITECTURE §4.1).

Every participating system — Cognito, DynamoDB, Aurora, S3, S3 Vectors, Glue, SES —
exposes exactly these five tools through AgentCore Gateway, and the agent never learns
there are eight backends. That is what makes this a platform rather than eight
integrations, and it is why the tool surface stays O(1) in participant count.

Python attributes are snake_case; the wire format is camelCase, generated by alias rather
than hand-maintained in two places. Dump with ``by_alias=True`` before canonicalising —
`digested_body()` does it for you.

This module imports nothing from `langgraph`, `langchain` or `boto3`, and must not start
(invariant 0). It survived two framework migrations and one cloud rewrite untouched.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, model_validator
from pydantic.alias_generators import to_camel

from pii_erasure.contract.archetypes import Archetype
from pii_erasure.contract.canonical import JSONValue
from pii_erasure.contract.outcomes import Deletability, Outcome


class Verb(str, Enum):
    """The five tools. `discover` and `verify` are read-only — invariant 1 depends on it."""

    DISCOVER = "subject.discover"
    SOFT_DELETE = "subject.soft_delete"
    RESTORE = "subject.restore"
    HARD_DELETE = "subject.hard_delete"
    VERIFY = "subject.verify"


#: The verbs a discovery agent may ever be offered. Invariant 1 is enforced in three
#: independent places; this constant is the one the subgraph asserts against at
#: construction (M7), and it exists here so the read-only set is defined by the contract
#: rather than by the agent that happens to consume it.
READ_ONLY_VERBS: frozenset[Verb] = frozenset({Verb.DISCOVER, Verb.VERIFY})

#: Verbs that change a participant's state, and therefore require a manifest digest.
MUTATING_VERBS: frozenset[Verb] = frozenset({Verb.SOFT_DELETE, Verb.RESTORE, Verb.HARD_DELETE})


class ContractModel(BaseModel):
    """Frozen, alias-generating, extra-forbidding base for every contract object.

    ``extra="forbid"`` is a security property, not tidiness: a participant response is
    parsed from a Lambda the agent does not control, and an unexpected field is a
    signal, not a nuisance. ``frozen=True`` means a request cannot be mutated between
    the policy check and the call.
    """

    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        frozen=True,
        extra="forbid",
        use_enum_values=False,
    )

    def digested_body(self) -> dict[str, JSONValue]:
        """The camelCase JSON form, ready for `canonical()`.

        Volatile keys are *not* stripped here — `canonical()` rejects them, and this
        method deliberately does not paper over that (canonical.py rule 5).
        """
        dumped: dict[str, Any] = self.model_dump(mode="json", by_alias=True)
        return dumped


class Artifact(ContractModel):
    """One thing that exists for a subject in one system."""

    kind: str = Field(description="row | object | user | vector | contact | …")
    locator: str = Field(description="Where it is, in that system's own vocabulary")
    count: int = Field(ge=0, default=1)
    classification: tuple[str, ...] = Field(default=())
    retention_until: str | None = Field(
        default=None,
        description="Statutory retention expiry, ISO-8601. A property of the artifact, "
        "not of the run that observed it — so it is not a volatile key.",
    )


class Residual(Artifact):
    """An artifact that could **not** be actioned, and why.

    Load-bearing (invariant 7). `notify-suppression` returns one for the SES suppression
    hash it is legally required to keep; `analytics-lake` for Iceberg rows that survive
    until snapshot expiry. Disclosed to the approver and carried into the certificate.
    """

    reason: str = Field(min_length=1, description="Why this could not be actioned, in plain words")


class Hold(ContractModel):
    """A legal hold. Blocks erasure of what it scopes, and is re-checked after the
    grace window rather than trusted from plan time (§5.3)."""

    hold_id: str
    authority: str
    scope: str
    basis: str = Field(description="e.g. GDPR Art.17(3)(e)")
    expires_at: str | None = Field(
        default=None, description="ISO-8601, or null for an open-ended hold"
    )


class DiscoveryEvidence(ContractModel):
    """What discovery actually looked at. `observed_at` is volatile by design: evidence
    accompanies a response, and never enters a digested body."""

    query_digest: str
    observed_at: str


class ReceiptEvidence(ContractModel):
    """What a mutation actually did. `applied_at` is volatile, as above."""

    receipt_digest: str
    applied_at: str


# ─── Requests ─────────────────────────────────────────────────────────────────────────


class DiscoverRequest(ContractModel):
    """Read-only. What exists for this subject here?"""

    subject_ref: str = Field(min_length=1, description="Pseudonymous handle — never raw PII")
    saga_id: str = Field(min_length=1)
    scope_hints: tuple[str, ...] = Field(
        default=(),
        description="Advisory only. A hint may reorder discovery; it may never cause a "
        "system to be skipped (ADR-019).",
    )


class VerifyRequest(ContractModel):
    """Read-only assertion, run after `hard_delete`. Must find nothing."""

    subject_ref: str = Field(min_length=1)
    saga_id: str = Field(min_length=1)


class MutationRequest(ContractModel):
    """Common shape of `soft_delete`, `restore` and `hard_delete`.

    `manifest_digest` is mandatory on every mutation: the participant re-validates it
    in-process even though AgentCore Policy already checked it at the Gateway. The
    Gateway is the control, the participant is the backstop, and a misconfigured target
    fails closed (§4.1).
    """

    subject_ref: str = Field(min_length=1)
    saga_id: str = Field(min_length=1)
    manifest_digest: str = Field(min_length=1, description="Binds this call to an approved plan")
    idempotency_key: str = Field(min_length=1, description="See idempotency.py")
    artifacts: tuple[Artifact, ...] = Field(description="Echo of the approved artifact set")
    dry_run: bool = False


class SoftDeleteRequest(MutationRequest):
    """Reversible: disable, tombstone, or mark pending-anonymization."""


class RestoreRequest(MutationRequest):
    """The compensating transaction for `soft_delete`.

    Unreachable from any phase-3 code path (invariant 6): a compensating transaction that
    recreates a subject's data converts a failed erasure into an active breach.
    """

    restore_token: str = Field(min_length=1)


class HardDeleteRequest(MutationRequest):
    """Irreversible: purge or crypto-shred.

    The approval token is required by the *type*, so "hard delete without an approval"
    is not a runtime check that a code path can skip — it fails to construct.
    """

    approval_token: str = Field(min_length=1, description="Digest-bound; see approval/ and ADR-006")


# ─── Responses ────────────────────────────────────────────────────────────────────────


class DiscoverResponse(ContractModel):
    """What one system holds for one subject."""

    system_id: str = Field(min_length=1)
    archetype: Archetype
    found: bool
    deletability: Deletability
    evidence: DiscoveryEvidence
    artifacts: tuple[Artifact, ...] = ()
    holds: tuple[Hold, ...] = ()

    @model_validator(mode="after")
    def _found_agrees_with_artifacts(self) -> DiscoverResponse:
        if self.found and not self.artifacts:
            raise ValueError("found=True with no artifacts — say what was found")
        if not self.found and self.artifacts:
            raise ValueError("found=False with artifacts — recall failures start here")
        # A hold may cover everything (BLOCKED_BY_HOLD) or only part of what was found
        # (PARTIAL). What it may never do is go unreported in the assessment.
        if self.holds and self.deletability not in (
            Deletability.BLOCKED_BY_HOLD,
            Deletability.PARTIAL,
        ):
            raise ValueError(
                f"holds present but deletability={self.deletability.value} — a hold the "
                "plan does not reflect is a hold the approver never sees"
            )
        return self


class MutationResponse(ContractModel):
    """The result of `soft_delete`, `restore` or `hard_delete`.

    The validator below is invariant 7 expressed as a type: `APPLIED` with residual work
    outstanding does not merely fail review, it fails to construct.
    """

    system_id: str = Field(min_length=1)
    outcome: Outcome
    affected: int = Field(ge=0)
    evidence: ReceiptEvidence
    residual: tuple[Residual, ...] = ()
    restore_token: str | None = Field(
        default=None, description="soft_delete only; opaque and TTL-bounded"
    )

    @model_validator(mode="after")
    def _residual_honesty(self) -> MutationResponse:
        if self.residual and self.outcome is not Outcome.PARTIAL:
            raise ValueError(
                f"outcome={self.outcome.value} with a populated residual — a participant "
                "that cannot fully delete returns PARTIAL (invariant 7)"
            )
        if self.outcome is Outcome.PARTIAL and not self.residual:
            raise ValueError("PARTIAL with an empty residual — say what remains")
        return self


class VerifyResponse(ContractModel):
    """The post-deletion assertion. `clean` is only true when nothing remains."""

    system_id: str = Field(min_length=1)
    clean: bool
    evidence: DiscoveryEvidence
    remaining: tuple[Artifact, ...] = ()

    @model_validator(mode="after")
    def _clean_means_empty(self) -> VerifyResponse:
        if self.clean and self.remaining:
            raise ValueError("clean=True with remaining artifacts — verify must find zero")
        return self
